[project]
name = "studipcalendarexportrenamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ics>=0.7.2",
    "textual-dev>=1.8.0",
    "textual>=6.3.0",
    "rich>=14.2.0",
]
